#ifndef VERSIONNO_H
#define VERSIONNO_H

#define DEF_VERSION_MAJOR   21
#define DEF_VERSION_MINOR   10
#define DEF_VERSION_PATCH   0
#define DEF_VERSION_TEST    1


#define FILE_VERSION_MAIN DEF_VERSION_MAJOR,DEF_VERSION_MINOR,DEF_VERSION_PATCH,DEF_VERSION_TEST

#define FILE_VERSION_STR "21. 10. 0\0"

#define FILE_COMMENT_STR "Helpdesk phone number +7 812 534-68-82\0"

#define FILE_COMPANY_STR "OOO IMC Micro\0"

#define FILE_PRODUCT_STR "Micro displacement meter\0"

#define ANOTHER_PRODUCT_STR "UV 21.10.0\0"

#endif // VERSIONNO_H
