#ifndef DETECTMODELCOMMANDS_H
#define DETECTMODELCOMMANDS_H

enum DETECTS_MODEL_CMDS
{
    NO = 0
    , CLEAR_LIST = 1
    , ADD_RECORD = 2
    , REMOVE_RECORD = 3
    , UPDATE_ACTIVE_STATE = 4
    , UPDATE_CURRENT_VALUE = 5
};

#endif // DETECTMODELCOMMANDS_H
